### ISSUE TITLE
XCode: ReadMe issue

### ISSUE THREAD

**Issue by tsmcgrath** [HyperARCo/Mirador#3]
Hi, looks super interesting. I went to install the package and noticed this message in XCode:
"Unable to load the ReadMe"

Did not load. I am an XCode and Swift newbie so it could be operator error.
`import Mirador` // Message: No such module 'Mirador'

M1 Macbook Pro
Ventura 13.3.1

**Comment by SunburstEnzo** [comment]
Hi @tsmcgrath! Do you mean it doesn't load the readme when trying to add the package? I just tried it myself and it seems to work fine – can you post screenshots maybe? Also you're using Xcode 14 and not the new 15.0 beta right?

<img width="504" alt="Mirador SPM - Unable to load readme" src="https://github.com/HyperARCo/Mirador/assets/1451896/00d38fc3-7c9f-45b7-ade2-66e773943e11">

**Comment by tsmcgrath** [comment]
Yep, operator error. I upgraded to  XCode 14.3.1. Started a new test. Added the package dependency and it imports fine. Sorry for the distraction.

**Comment by SunburstEnzo** [comment]
No worries at all, glad to hear it's working for you! Feel free to open another issues if you have any other concerns or feature improvements.
